/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Chat.java
 *
 * Created on 19-Mar-2010, 11:58:04 AM
 */

/**
 *
 * @author Phil
 */

import java.awt.Color;
import javax.swing.BorderFactory;
import java.awt.Cursor;

public class Chat extends javax.swing.JFrame {

    /** Creates new form Chat */
    public Chat() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatPanel = new javax.swing.JPanel();
        sendButton = new javax.swing.JButton();
        messageArea = new java.awt.List();
        feedbackArea = new java.awt.List();
        writingArea = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(240, 240, 240));

        chatPanel.setOpaque(false);
	chatPanel.setPreferredSize(GameBoard.chatPanelSize);
	chatPanel.setBorder(BorderFactory.createLineBorder(Color.black));

        sendButton.setBackground(new java.awt.Color(53, 212, 160));
        sendButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sendButton.setText("Send");
        sendButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        sendButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        messageArea.setBackground(new java.awt.Color(230, 230, 230));

        feedbackArea.setBackground(new java.awt.Color(230, 230, 230));

        writingArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                writingAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                writingAreaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addGroup(chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chatPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(messageArea, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addGroup(chatPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(feedbackArea, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chatPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(writingArea, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chatPanelLayout.createSequentialGroup()
                        .addContainerGap(173, Short.MAX_VALUE)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageArea, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedbackArea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(writingArea, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String message = writingArea.getText();
        writingArea.setText("");
        messageArea.add("Philippe says:");
        messageArea.add(message);

    }//GEN-LAST:event_sendButtonActionPerformed

    private void writingAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_writingAreaFocusLost
        feedbackArea.removeAll();
}//GEN-LAST:event_writingAreaFocusLost

    private void writingAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_writingAreaFocusGained
        feedbackArea.add("Philippe is typing ... ");
}//GEN-LAST:event_writingAreaFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel chatPanel;
    private java.awt.List feedbackArea;
    private java.awt.List messageArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JEditorPane writingArea;
    // End of variables declaration//GEN-END:variables

}
